[package]
name = "elgamal_practice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rand_chacha = "0.3.1"
num-traits = "0.2.15"
dialoguer = "0.10.4"
anyhow = "1.0.71"
blake3 = "1.3.3"